networks:
  my_network:
    name: inception-net
    driver: bridge

volumes:
  wordpress-volume:
    driver_opts:
      type: none
      device: '/home/sohan/data/wordpress'
      o: bind

  database-volume:
    driver_opts:
      type: none
      device: '/home/sohan/data/mariadb'
      o: bind

services:
  nginx:
    image: nginx-inception:1.0
    build:
      context: ./requirements/nginx/
    networks:
      - my_network
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb-inception:1.0
    build:
      context: ./requirements/mariadb/
    networks:
      - my_network
    container_name: mariadb
    ports:
      - "3306"
    volumes:
      - database-volume:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on: 
      - mariadb
    image: wordpress-inception:1.0
    build:
      context: ./requirements/wordpress/
    networks:
      - my_network
    container_name: wordpress
    ports:
      - "9000"
    volumes:
      - wordpress-volume:/var/www/html/wordpress
    env_file:
      - .env
    restart: always