networks:
  my_network:
    name: inception-net
    driver: bridge

services:
  nginx:
    image: nginx:inception
    init: true
    build:
      context: ./requirements/nginx/
    networks:
      - my_network
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/sohan/data/wordpress
        target: /var/www/html/wordpress
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb:inception
    init: true
    build:
      context: ./requirements/mariadb/
    networks:
      - my_network
    container_name: mariadb
    ports:
      - "3306"
    volumes:
      - type: bind
        source: /home/sohan/data/mariadb
        target: /var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on: 
      - mariadb
    image: wordpress:inception
    init: true
    build:
      context: ./requirements/wordpress/
    networks:
      - my_network
    container_name: wordpress
    ports:
      - "9000"
    volumes:
      - type: bind
        source: /home/sohan/data/wordpress
        target: /var/www/html/wordpress
    env_file:
      - .env
    restart: always